# Generated by Django 5.1.1 on 2024-12-04 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorhub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="grade_levels",
            field=models.ManyToManyField(blank=True, to="tutorhub.gradelevel"),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="subjects",
            field=models.ManyToManyField(blank=True, to="tutorhub.subject"),
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="credentials/")),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="tutorhub.tutor",
                    ),
                ),
            ],
        ),
    ]
