# Generated by Django 5.1.4 on 2025-01-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorhub", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_spotlight",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_birthdate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="show_full_name",
            field=models.BooleanField(default=False),
        ),
    ]
