# Generated by Django 5.1.1 on 2024-12-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorhub", "0002_message_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
