# Generated by Django 5.1.4 on 2025-01-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorhub", "0003_user_missing_profile_data_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
