# Generated by Django 5.1.1 on 2024-12-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorhub", "0003_message_edited_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
