# Generated by Django 5.1.4 on 2025-01-06 21:17

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutorhub", "0005_alter_user_middle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, null=True, region=None
            ),
        ),
    ]
